name: Node.js Release

on:
  push:
    tags:
      - '*-v*.*.*'

jobs:
  get:
    runs-on: ubuntu-latest

    outputs:
      package_name: ${{ steps.get_name.outputs.name }}

    steps:
      - name: Get Package Name
        id: get_name
        run: |
          echo "name=$(echo ${GITHUB_REF#refs/tags/} | awk -F '-v' '{print $1}')" >> "$GITHUB_OUTPUT"

  publish:
    runs-on: ubuntu-latest
    needs: get
    env:
      PACKAGE_NAME: '@kuoruan/${{ needs.get.outputs.package_name }}'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Publish to NPM
        run: pnpm publish --filter "${{ env.PACKAGE_NAME }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Setup Node.js for GitHub Packages
      #   uses: actions/setup-node@v3
      #   with:
      #     registry-url: 'https://npm.pkg.github.com'

      # - name: Publish to GitHub Packages
      #   run: pnpm publish --filter "${{ env.PACKAGE_NAME }}"
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GHA_PAT }}

